// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ------ //
// matrix //
// ------ //

#define matrix_wrap_target 0
#define matrix_wrap 4

static const uint16_t matrix_program_instructions[] = {
            //     .wrap_target
    0x4008, //  0: in     pins, 8                    
    0xa0e6, //  1: mov    osr, isr                   
    0x6008, //  2: out    pins, 8                    
    0xe001, //  3: set    pins, 1                    
    0xe000, //  4: set    pins, 0                    
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program matrix_program = {
    .instructions = matrix_program_instructions,
    .length = 5,
    .origin = -1,
};

static inline pio_sm_config matrix_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + matrix_wrap_target, offset + matrix_wrap);
    return c;
}
#endif

