// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ---------- //
// squarewave //
// ---------- //

#define squarewave_wrap_target 2
#define squarewave_wrap 4

static const uint16_t squarewave_program_instructions[] = {
    0xe081, //  0: set    pindirs, 1                 
    0xe030, //  1: set    x, 16                      
            //     .wrap_target
    0x8080, //  2: pull   noblock                    
    0xe101, //  3: set    pins, 1                [1] 
    0xe000, //  4: set    pins, 0                    
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program squarewave_program = {
    .instructions = squarewave_program_instructions,
    .length = 5,
    .origin = -1,
};

static inline pio_sm_config squarewave_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + squarewave_wrap_target, offset + squarewave_wrap);
    return c;
}
#endif

